Nes 12 table controller
SDU-Sem3-G1-NES/Project pull request #18
Opened 2024-10-28 09:14 UTC by DovydasGan

2024-10-28 09:35 UTC, nicki419 requested changes
Please implement the requested changes.

2024-10-28 09:35 UTC, nicki419 commented on TableController/ITable.cs
> +        float Height { get; set; }
Int is good enough accuracy here

2024-10-28 09:35 UTC, nicki419 commented on TableController/ITableController.cs
> +        float GetTableHeight(ITable Table);
Instead of the methods requiring an ITable object to be injected, you can inject an ITable as a property of ITableController

e.g. private ITable table;

2024-10-28 09:35 UTC, nicki419 commented on TableController/ITableController.cs
> +        List<ITableError> GetTableError();
It might make more sense to simply expose the list publicly.
```suggestion
        public List<ITableError> {get; private set; }
```

2024-10-28 09:35 UTC, nicki419 commented on TableController/ITableController.cs
> +        int GetActivationCounter();
We might not need this from the Table API. Saving this information ourselves gives us more control.

2024-10-28 09:35 UTC, nicki419 commented on TableController/LinakTable.cs
> +        public string Manufacturer { get; set; }
Can be hardcoded to "Linak" in the constructor

2024-10-28 09:35 UTC, nicki419 commented on TableController/LinakTable.cs
> +        public float Height { get; set; }
```suggestion
        public int Height { get; private set; }
```

2024-10-28 09:35 UTC, nicki419 commented on TableController/LinakTable.cs
> +    }
Class needs constructor

2024-10-28 09:35 UTC, nicki419 commented on TableController/ITableController.cs
> +}
Just add all methods from the LinakTable API here. Classes that do not implement these methods can throw a NotImplemented Exception.

2024-10-28 09:35 UTC, nicki419 commented on TableController/LinakTable.cs
> +        public int SitStandCounter { get; set; }
Might be best to create a small class to save this info.

2024-10-28 09:35 UTC, nicki419 commented on TableController/LinakTableController.cs
> +    {
Needs events for collision detection

2024-10-28 12:15 UTC, s1masy commented on TableController/LinakTable.cs
> +}
Made a class to use in LinakTable insted of an interface, because I cant figure out how to set default values in the constructor otherwise. Is this ok?

2024-10-30 16:23 UTC, nicki419 approved these changes

2024-10-30 16:23 UTC, merged