NES-28 Added login page and database authentication
SDU-Sem3-G1-NES/Project pull request #29
Opened 2024-11-03 19:13 UTC by benasbart

2024-11-03 21:54 UTC, nicki419 requested changes

2024-11-03 21:54 UTC, nicki419 commented on DataAccess/_Setup/GenerateUser.py
> +    fixed_salt = b"$2b$12$VKSaJPoloZwgNhNqMJFxfu"
Secret should not be in code. Maybe move to .env. Don't forget to put it in EXAMPLE.env too

2024-11-03 21:54 UTC, nicki419 commented on Famicom/Components/Pages/Login.razor.cs
> +namespace Famicom.Components.Pages
Please move all logic to a class in Famicom.Models. have the controller (this file) only handle data binding, not actual logic. Same with the other razor.cs files

2024-11-03 21:54 UTC, nicki419 commented on Famicom/Models/LoginModel.cs
> +        public string Password { get; set; } = string.Empty;
Sensible data should not be public. I think hashing the username and password is the one thing we should do in the razor.cs file. So the puretext email and password never leave the class.

2024-11-03 21:54 UTC, nicki419 commented on Famicom/Program.cs
> +builder.Services.AddScoped<UserRepository>();
Why do we need this here? Can this be moved to models?

2024-11-03 21:54 UTC, nicki419 commented on DataAccess/UserRepository.cs
> +                        return BitConverter.ToString(passwordHashBytes).Replace("-", "").ToLower();
Why are we replacing characters here, and making the hash lowercase? That does not seem like a sound thing to do

2024-11-03 21:54 UTC, nicki419 commented on Famicom/Components/Pages/Login.razor.cs
> +        private readonly string fixedSalt = "$2b$12$VKSaJPoloZwgNhNqMJFxfu"; // Fixed salt for consistent hashing
Should be moved to .env

2024-11-06 17:18 UTC, benasbart reviewed
fixed, now salt is stored encoded in base64 in the .env. (its encoded because it wasnt possible to read the salt since it has dollar signs and the dotenv library parses the dollar signs as smth else)

2024-11-06 17:22 UTC, benasbart reviewed
Moved all the logic regarding database to UserCredentialServices

2024-11-06 17:24 UTC, benasbart commented on Famicom/Components/Pages/Login.razor.cs
> +namespace Famicom.Components.Pages
Moved logic to UserCredentialsService

2024-11-06 17:25 UTC, benasbart commented on Famicom/Models/LoginModel.cs
> +        public string Password { get; set; } = string.Empty;
made protected

2024-11-06 17:25 UTC, benasbart commented on Famicom/Program.cs
> +builder.Services.AddScoped<UserRepository>();
Removed.

2024-11-06 17:25 UTC, benasbart commented on Famicom/Components/Pages/Login.razor.cs
> +        private readonly string fixedSalt = "$2b$12$VKSaJPoloZwgNhNqMJFxfu"; // Fixed salt for consistent hashing
Moved

2024-11-08 14:53 UTC, benasbart commented on Models/Services/UserCredentialsService.cs
> +        fixedSalt = Encoding.UTF8.GetString(Convert.FromBase64String(base64Salt));
Done. UserCredentialsService returns "$2b$12$VKSaJPoloZwgNhNqMJFxfu", and python script returns "b'$2b$12$VKSaJPoloZwgNhNqMJFxfu'", but they are used the same and hashed credentials match.

2024-11-11 09:30 UTC, nicki419 approved these changes

2024-11-11 09:30 UTC, merged