Table Component
SDU-Sem3-G1-NES/Project pull request #30
Opened 2024-11-04 19:16 UTC by Tokushiro

-Split table into tableComponent for reusability.
- Added GetAllTables Method to userRepository to get all tables without filter

2024-11-05 12:50 UTC, nicki419 requested changes
Please implement the changes requested, then you may merge.

2024-11-05 12:50 UTC, nicki419 commented on Famicom/Components/Pages/TableComponent.razor
> +<MudCard>
Please fix the indentation in this file.

2024-11-05 12:50 UTC, nicki419 commented on Famicom/Components/Pages/TableComponent.razor.cs
> +        public string TableTitle { get; set; } = "Manage Your Table";
That should be the title of the page, not the table component.

2024-11-05 12:50 UTC, nicki419 commented on Famicom/Components/Pages/TableComponent.razor
> +            <MudText Typo="Typo.body1">Table Name: @Table.Name</MudText>
Three dereference warnings need to be addressed.

2024-11-05 12:50 UTC, nicki419 commented on Famicom/Components/Pages/TableComponent.razor
> +        <MudCardHeader>
This is the title of the page, not the component. Imagine The admin will see "Manage Your Table" on every single table.

2024-11-06 19:00 UTC, Tokushiro commented on Famicom/Components/Pages/TableComponent.razor.cs
> +        public string TableTitle { get; set; } = "Manage Your Table";
> That should be the title of the page, not the table component.

Moved that to table and created mock method to give title based on user type

2024-11-06 19:00 UTC, Tokushiro commented on Famicom/Components/Pages/TableComponent.razor
> +<MudCard>
Fixed

2024-11-06 19:01 UTC, Tokushiro commented on Famicom/Components/Pages/TableComponent.razor
> +        <MudCardHeader>
> This is the title of the page, not the component. Imagine The admin will see "Manage Your Table" on every single table.

Done like I said before I created mock method to get tittle based on user type, as of now it will only return Admin Panel

2024-11-06 19:13 UTC, Tokushiro commented on Famicom/Components/Pages/TableComponent.razor
> +            <MudText Typo="Typo.body1">Table Name: @Table.Name</MudText>
Fixed most of the warnings only left one from the dashboard.

2024-11-08 07:37 UTC, nicki419 commented on Famicom/Components/Pages/TableComponent.razor.cs
> +        private TableModel ?tableModel { get; set; }
Question mark behind type, not in front of variable name

```suggestion
        private TableModel? tableModel { get; set; }
```

2024-11-08 07:37 UTC, nicki419 commented on Famicom/Components/Pages/TableComponent.razor.cs
> +        public ITable ?Table { get; set; }
```suggestion
        public ITable? Table { get; set; }
```

2024-11-08 07:38 UTC, nicki419 commented on Famicom/Models/UserModel.cs
> +        //private IUser? user;
Do not leave commented code around

2024-11-08 07:45 UTC, nicki419 requested changes
You've got 8 MUD0002 Warnings in Dashboard.razor that need to be resolved. 
e.g.

```
/home/nick/Desktop/Uni/SDU Semester 3/Semester Project/Project/Famicom/Components/Pages/Dashboard.razor(1,1): warning MUD0002: Illegal Attribute 'T' on 'MudChart' using pattern 'LowerCase' source location '(350,32)-(350,80)' (https://mudblazor.com/features/analyzers) [/home/nick/Desktop/Uni/SDU Semester 3/Semester Project/Project/Famicom/Famicom.csproj]
```

2024-11-08 08:42 UTC, nicki419 approved these changes

2024-11-08 08:42 UTC, merged